routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TestcentreController;
use App\Http\Controllers\DoctorController;
use App\Http\Controllers\HospitalController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('doctor', DoctorController::class);
Route::resource('hospital', HospitalController::class);
Route::resource('testcentre', TestcentreController::class);
// Route::get('/testcentres',[TestController::class, 'index']);
Route::get('/', function () {
    return view('front.index');
});
Route::get('/dashboard', function(){ 
    $sidebarSection = "dashboard";
    $sidebarSubSection ="";
    return view('dashboard.index',compact([
            'sidebarSection',
            'sidebarSubSection'
        ])); 
 })->name('dashboard.index');

Route::get('/manage-doctors', [DoctorController::class , 'index'])->name('doctors.index');
Route::get('/approved-doctors', [DoctorController::class , 'approvedDoctors'])->name('doctors.showApproved');
Route::get('/rejected-doctors', [DoctorController::class , 'rejectedDoctors'])->name('doctors.showRejected');
Route::get('/accept-doctor/{id}', [DoctorController::class , 'accepted'])->name('doctors.accepted');
Route::post('/reject-doctor/{id}', [DoctorController::class , 'rejected'])->name('doctors.rejected');

Route::get('/manage-hospitals', [HospitalController::class , 'index'])->name('hospitals.index');
Route::get('/approved-hospitals', [HospitalController::class , 'approvedhospitals'])->name('hospitals.showApproved');
Route::get('/rejected-hospitals', [HospitalController::class , 'rejectedhospitals'])->name('hospitals.showRejected');
Route::get('/accept-hospital/{id}', [HospitalController::class , 'accepted'])->name('hospitals.accepted');
Route::post('/reject-hospital/{id}', [HospitalController::class , 'rejected'])->name('hospitals.rejected');

Route::get('/manage-testcentres', [TestcentreController::class , 'index'])->name('testcentres.index');
Route::get('/approved-testcentres', [TestcentreController::class , 'approvedtestcentres'])->name('testcentres.showApproved');
Route::get('/rejected-testcentres', [TestcentreController::class , 'rejectedtestcentres'])->name('testcentres.showRejected');
Route::get('/accept-testcentre/{id}', [TestcentreController::class , 'accepted'])->name('testcentres.accepted');
Route::post('/reject-testcentre/{id}', [TestcentreController::class , 'rejected'])->name('testcentres.rejected');


Route::get('/article1', function () { return view('front.article1'); })->name('article1');
Route::get('/article2', function () { return view('front.article2'); })->name('article2');
Route::get('/article3', function () { return view('front.article3'); })->name('article3');
Route::get('/article4', function () { return view('front.article4'); })->name('article4');
Route::get('/article5', function () { return view('front.article5'); })->name('article5');

Route::get('/registerDoctor', function () { return view('front.doctor_form'); })->name('doctor_form');
Route::get('/registerHospital', function () { return view('front.hosp_form'); })->name('hospital_form');
Route::get('/registerTestCentre', function () { return view('front.testcnt_form'); })->name('testcentre_form');



Auth::routes();
Route::get('/signin', function () { 
    if(auth())
    return view('front.login'); 
    else
    return redirect(route('home'));
})->name('signin');
Route::get('/signup', function () { 
    if(auth())
    return view('front.register'); 
    else
    return redirect(route('home'));
 })->name('signup');

Route::get('/home', function () { return view('front.index'); })->name('home');

resources/views/front/doctor_form.blade.php
<html>
<title>registration Form</title>
<body>
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Covi-Care</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

   <!-- Favicons -->
   <link href="{{asset('assetsfe/assets/img/favicon.png')}}" rel="icon">
  <link href="{{asset('assetsfe/assets/img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{asset('assetsfe/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/venobox/venobox.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/animate.css/animate.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('assetsfe/assets/css/style.css')}}" rel="stylesheet">

    

<style>
*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  font-family: 'Nunito', sans-serif;
  color: #384047;
}

form {
  max-width: 300px;
  margin: 100px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
}

h1 {
  margin: 0 0 15px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 5px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 10px;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

button {
  padding: 19px 39px 18px 39px;
  color: #F9f9f9;
  background-color: #4bc970;
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width: 100%;
  border: 1px solid #3ac162;
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
  margin-bottom: 10px;
}

fieldset {
  margin-bottom: 10px;
  border: none;
}

legend {
  font-size: 1.2em;
  margin-bottom: 3px;
  color:blue;
}

label {
  display: block;
  margin-bottom: 2px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 25px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 20px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

@media screen and (min-width: 480px) {

  form {
    max-width: 480px;
  }

}
</style>
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="{{route('home')}}">COVI-Care</a></h1>
    

      <nav class="nav-menu d-none d-lg-block">
        <ul>
              
        
          <li class="drop-down"><a href="">For Providers</a>
          <ul>
             
             <li><a href="{{route('hospital_form')}}">Register as a Hospital</a></li>
             <li><a href="{{route('signup')}}">Register as a User</a></li>
             <li><a href="{{route('testcentre_form')}}">Register as a Test Center</a></li>
           </ul>
          </li>
            
        

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{{route('signin')}}" class="appointment-btn scrollto">Login/SignUp</a>

    </div>
  </header><!-- End Header -->
  
      <form action="{{route('doctor.store')}}" method="POST">
        @csrf
        <h1>Register As A Doctor</h1>
        
        <fieldset>
          
          <label for="name">Full Name:</label>
          <input type="text" id="name" name="name"  class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}"  placeholder="Full Name">

          @error('name')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
          
          <label for="mail">Email:</label>
          <input type="email" id="email" name="email"  class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"  placeholder="Email">

          @error('email')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
          
          <label for="phone">Phone:</label>
          <input type="text" id="phone" name="phone"  class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}"  placeholder="Phone">

          @error('phone')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror

          <label for="experience">Field of Experience:</label>
          <input type="number" id="experience" name="experience"  class="form-control @error('experience') is-invalid @enderror" value="{{ old('experience') }}"  placeholder="Experience">

          @error('experience')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror

          <label for="expertise">Expertise:</label>
          <select id="expertise" name="expertise" class="form-control @error('expertise') is-invalid @enderror" value="{{ old('expertise') }}"> 
          <optgroup label="Choose A Specialization">
          <option value="lungs">Lungs</option>
            <option value="neuro">Neuro</option>
            <option value="heart">Heart</option>
     </optgroup></select>
    
          @error('expertise')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror

          </fieldset>
        
        <fieldset>
          <legend><span class="number">2</span>Your Work Profile</legend>
          <label>Clinic/Hospital Name:</label>
          <input type="text" id="work_name" name="work_name"  class="form-control @error('work_name') is-invalid @enderror" value="{{ old('work_name') }}"  placeholder="Clinic/Hospital Name">

          @error('work_name')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror

		  
		  <label for="work_city">Clinic/Hospital City:</label>
            <select id="work_city" name="work_city" class="form-control @error('work_city') is-invalid @enderror" value="{{ old('work_city') }}"> 
          <optgroup label="Choose A City">
          <option value="mumbai">Mumbai</option>
            <option value="pune">Pune</option>
            <option value="delhi">Delhi</option>
            <option value="kolkata"> Kolkata</option>
            <option value="hyderabad">Hyderabad</option>
            <option value="chennai">Chennai</option>
            <option value="indore">Indore</option>
            <option value="ahemdabad">Ahemdabad</option>
            <option value="lucknow">Lucknow</option>
     </optgroup></select>
     
         @error('work_city')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  	  
			   <label >Clinic/Hospital Pin Code: </label>
         <input type="number" id="work_pincode" name="work_pincode"  class="form-control @error('work_pincode') is-invalid @enderror" value="{{ old('work_pincode') }}"  placeholder="Pincode">

          @error('work_pincode')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  
          
          <label for="work_phone">Clinic/Hospital Phone:</label>
          <input type="text" id="work_phone" name="work_phone"  class="form-control @error('work_phone') is-invalid @enderror" value="{{ old('work_phone') }}"  placeholder="Phone">

          @error('work_phone')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  
        </fieldset>
         	  
		 <button type="submit">Register</button>
      </form>
<!-- ======= Footer ======= -->
<footer id="footer">

<div class="footer-top">
  <div class="container">
    <div class="row">

      <div class="col-lg-3 col-md-6 footer-contact">
        <h3>Covi-Care</h3>
        <p>
          A108 Adam Street <br>
          New York, NY 535022<br>
          United States <br><br>
          <strong>Phone:</strong> +1 5589 55488 55<br>
          <strong>Email:</strong> info@example.com<br>
        </p>
      </div>

      <div class="col-lg-2 col-md-6 footer-links">
        <h4>About Us</h4>
        <ul>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
        </ul>
      </div>

      <div class="col-lg-3 col-md-6 footer-links">
        <h4>Our Services</h4>
      
      </div>

      <div class="col-lg-4 col-md-6 footer-newsletter">
        <h4>Subscribe For Daily Updates</h4>
       
        <form action="" method="post">
          <input type="email" name="email"><input type="submit" value="Subscribe">
        </form>
      </div>

    </div>
  </div>
</div>

<div class="container d-md-flex py-4">


  <div class="social-links text-center text-md-right pt-3 pt-md-0">
    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
  </div>
</div>
</footer><!-- End Footer -->
<!-- Vendor JS Files -->
<script src="{{asset('assetsfe/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/venobox/venobox.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/counterup/counterup.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{asset('assetsfe/assets/js/main.js')}}"></script>
      
</body>
</html>
			
			

resources/views/front/hosp_form.blade.php
<html>
<title>registration Form</title>
<body>
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Covi-Care</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

   <!-- Favicons -->
   <link href="{{asset('assetsfe/assets/img/favicon.png')}}" rel="icon">
  <link href="{{asset('assetsfe/assets/img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{asset('assetsfe/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/venobox/venobox.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/animate.css/animate.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{asset('assetsfe/assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('assetsfe/assets/css/style.css')}}" rel="stylesheet">

<style>
*, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  font-family: 'Nunito', sans-serif;
  color: #384047;
}

form {
  max-width: 300px;
  margin: 100px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
}

h1 {
  margin: 0 0 15px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 5px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 10px;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

button {
  padding: 19px 39px 18px 39px;
  color: #F9f9f9;
  background-color: #4bc970;
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width: 100%;
  border: 1px solid #3ac162;
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
  margin-bottom: 10px;
}

fieldset {
  margin-bottom: 10px;
  border: none;
}

legend {
  font-size: 1.2em;
  margin-bottom: 3px;
  color:blue;
}

label {
  display: block;
  margin-bottom: 2px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 25px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 20px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

@media screen and (min-width: 480px) {

  form {
    max-width: 480px;
  }

}
</style>
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="{{route('home')}}">COVI-Care</a></h1>
    

      <nav class="nav-menu d-none d-lg-block">
        <ul>
              
        
          <li class="drop-down"><a href="">For Providers</a>
          <ul>
             
             <li><a href="{{route('signup')}}">Register as a User</a></li>
             <li><a href="{{route('doctor_form')}}">Register as a Doctor</a></li>
             <li><a href="{{route('testcentre_form')}}">Register as a Test Center</a></li>
           </ul>
          </li>
            
        

        </ul>
      </nav><!-- .nav-menu -->

      <a href="{{route('signin')}}" class="appointment-btn scrollto">Login/SignUp</a>

    </div>
  </header><!-- End Header -->
      <form action="{{route('hospital.store')}}" method="POST">
        @csrf
        <h1>Register As A Hospital</h1>
        
        <fieldset>
          
          <label for="name">Full Name:</label>
          <input type="text" id="name" name="name"  class="form-control @error('name') is-invalid @enderror" value="{{ old('name') }}"  placeholder="Hospital Name">

          @error('name')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
          
          <label for="mail">Email:</label>
          <input type="email" id="email" name="email"  class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}"  placeholder="Email">

          @error('email')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
          
          <label for="phone">Phone:</label>
          <input type="text" id="phone" name="phone"  class="form-control @error('phone') is-invalid @enderror" value="{{ old('phone') }}"  placeholder="Phone">

          @error('phone')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  
		  <label for="city">City:</label>
            <select id="city" name="city" class="form-control @error('city') is-invalid @enderror" value="{{ old('city') }}"> 
          <optgroup label="Choose A City">
          <option value="mumbai">Mumbai</option>
            <option value="pune">Pune</option>
            <option value="delhi">Delhi</option>
            <option value="kolkata"> Kolkata</option>
            <option value="hyderabad">Hyderabad</option>
            <option value="chennai">Chennai</option>
            <option value="indore">Indore</option>
            <option value="ahemdabad">Ahemdabad</option>
            <option value="lucknow">Lucknow</option>
     </optgroup></select>
     
         @error('city')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  	  
			   <label >Pin Code: </label>
         <input type="number" id="pincode" name="pincode"  class="form-control @error('pincode') is-invalid @enderror" value="{{ old('pincode') }}"  placeholder="Pincode">

          @error('pincode')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  
          
          <label for="max_doctors">Max doctors Available:</label>
          <input type="number" id="max_doctors" name="max_doctors"  class="form-control @error('max_doctors') is-invalid @enderror" value="{{ old('max_doctors') }}"  placeholder="Max doctors">

          @error('max_doctors')
              <span class="invalid-feedback" role="alert">
                  <strong>{{ $message }}</strong>
              </span>
          @enderror
		  
        </fieldset>
         	  
		 <button type="submit">Register</button>
      </form>
      
<!-- ======= Footer ======= -->
<footer id="footer">

<div class="footer-top">
  <div class="container">
    <div class="row">

      <div class="col-lg-3 col-md-6 footer-contact">
        <h3>Covi-Care</h3>
        <p>
          A108 Adam Street <br>
          New York, NY 535022<br>
          United States <br><br>
          <strong>Phone:</strong> +1 5589 55488 55<br>
          <strong>Email:</strong> info@example.com<br>
        </p>
      </div>

      <div class="col-lg-2 col-md-6 footer-links">
        <h4>About Us</h4>
        <ul>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
          <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
        </ul>
      </div>

      <div class="col-lg-3 col-md-6 footer-links">
        <h4>Our Services</h4>
      
      </div>

      <div class="col-lg-4 col-md-6 footer-newsletter">
        <h4>Subscribe For Daily Updates</h4>
       
        <form action="" method="post">
          <input type="email" name="email"><input type="submit" value="Subscribe">
        </form>
      </div>

    </div>
  </div>
</div>

<div class="container d-md-flex py-4">


  <div class="social-links text-center text-md-right pt-3 pt-md-0">
    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
  </div>
</div>
</footer><!-- End Footer -->
<!-- Vendor JS Files -->
<script src="{{asset('assetsfe/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/venobox/venobox.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/counterup/counterup.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
  <script src="{{asset('assetsfe/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{asset('assetsfe/assets/js/main.js')}}"></script>
      
</body>
</html>
			
			